Update streamlit_app.py
Changes to deal with the error about pysqlite3 / sqlite3 
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0